title: Luscinia
description: Eco-jardin & Biodiversité
# This is crucial for GitHub Pages to make links work correctly
# If your repo is named "username.github.io", keep baseurl empty: ""
# If your repo is named "my-project", set baseurl: "/my-project"
baseurl: "" 
url: "https://htdev-clients.github.io"
baseurl: "/luscinia"
plugins:
  - jekyll-seo-tag